sudo: required
services:
  - docker

before_install:
  - docker build -t ciomaire/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ciomaire/docker-react npm run test -- --coverage

deploy:
  #edge: true
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-573206764893"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
